name: bryon
favicon: null
layout_spectrum: 0.025838444475084543
typography_spectrum: 0.21189016313292086
title: Bryon McCartney
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.12786776362918317
  lightness: 0.2544434769079089
  saturation: 0.8248736106324941
  rhythmicContrast: 0.9110961921978742
purpose: []
